server:
  port: 0

spring:
  application:
    name: uniquone-post-service

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true

  datasource:
    url: ${UNIQUONE_DB_URL}
    username: ${UNIQUONE_DB_ID}
    password: ${UNIQUONE_DB_PWD}
    driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA-SERVER}

greeting:
  message: Welcome to the Simple E-commerce

